service: dyndns

useDotenv: true
variablesResolutionMode: 20210326

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-certificate-creator
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'production'}
  region: ${opt:region, 'ap-southeast-2'}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "route53:ListHostedZones"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "route53:ChangeResourceRecordSets"
          Resource: "*"
  lambdaHashingVersion: 20201221


custom:
  customDomain:
    domainName: ${env:API_HOSTNAME}
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: http
  customCertificate:
    certificateName: ${env:API_HOSTNAME}
    hostedZoneNames: ${env:API_ZONENAME}.
    region: ${self:provider.region}

functions:
  dyndns:
    handler: src/handler.dyndns
    events:
      - httpApi: 'GET /nic/update'
